/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class RenERC20LogicV1 extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): RenERC20LogicV1;
  address: string;
  methods: {
    DOMAIN_SEPARATOR(): TransactionObject<string>;

    PERMIT_TYPEHASH(): TransactionObject<string>;

    _rateScale(): TransactionObject<string>;

    allowance(owner: string, spender: string): TransactionObject<string>;

    approve(
      spender: string,
      amount: number | string
    ): TransactionObject<boolean>;

    balanceOf(account: string): TransactionObject<string>;

    balanceOfUnderlying(_account: string): TransactionObject<string>;

    blacklistRecoverableToken(_token: string): TransactionObject<void>;

    burn(_from: string, _amount: number | string): TransactionObject<void>;

    claimOwnership(): TransactionObject<void>;

    decimals(): TransactionObject<string>;

    decreaseAllowance(
      spender: string,
      subtractedValue: number | string
    ): TransactionObject<boolean>;

    exchangeRateCurrent(): TransactionObject<string>;

    fromUnderlying(
      _amountUnderlying: number | string
    ): TransactionObject<string>;

    increaseAllowance(
      spender: string,
      addedValue: number | string
    ): TransactionObject<boolean>;

    initialize(
      name: string,
      symbol: string,
      decimals: number | string
    ): TransactionObject<void>;

    isOwner(): TransactionObject<boolean>;

    mint(_to: string, _amount: number | string): TransactionObject<void>;

    name(): TransactionObject<string>;

    nonces(arg0: string): TransactionObject<string>;

    owner(): TransactionObject<string>;

    pendingOwner(): TransactionObject<string>;

    permit(
      holder: string,
      spender: string,
      nonce: number | string,
      expiry: number | string,
      allowed: boolean,
      v: number | string,
      r: string | number[],
      s: string | number[]
    ): TransactionObject<void>;

    recoverTokens(_token: string): TransactionObject<void>;

    renounceOwnership(): TransactionObject<void>;

    setExchangeRate(_nextRate: number | string): TransactionObject<void>;

    symbol(): TransactionObject<string>;

    toUnderlying(_amount: number | string): TransactionObject<string>;

    totalSupply(): TransactionObject<string>;

    transfer(
      recipient: string,
      amount: number | string
    ): TransactionObject<boolean>;

    transferFrom(
      sender: string,
      recipient: string,
      amount: number | string
    ): TransactionObject<boolean>;

    transferOwnership(newOwner: string): TransactionObject<void>;

    version(): TransactionObject<string>;
  };
  events: {
    Approval: ContractEvent<{
      owner: string;
      spender: string;
      value: string;
      0: string;
      1: string;
      2: string;
    }>;
    LogRateChanged: ContractEvent<string>;
    OwnershipTransferred: ContractEvent<{
      previousOwner: string;
      newOwner: string;
      0: string;
      1: string;
    }>;
    Transfer: ContractEvent<{
      from: string;
      to: string;
      value: string;
      0: string;
      1: string;
      2: string;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
