/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import Contract, { contractOptions } from "web3/eth/contract";
import { EventLog, Callback, EventEmitter } from "web3/types";
import { TransactionObject, BlockType } from "web3/eth/types";
import { ContractEvent } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class DEX extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: contractOptions
  );
  clone(): DEX;
  address: string;
  methods: {
    ethereum(): TransactionObject<string>;

    BaseToken(): TransactionObject<string>;

    reserves(arg0: string): TransactionObject<string>;

    recoverTokens(_token: string): TransactionObject<void>;

    registerReserve(_erc20: string, _reserve: string): TransactionObject<void>;

    trade(
      _to: string,
      _src: string,
      _dst: string,
      _sendAmount: number | string
    ): TransactionObject<BN>;

    calculateReceiveAmount(
      _src: string,
      _dst: string,
      _sendAmount: number | string
    ): TransactionObject<BN>;
  };
  events: {
    LogTrade: ContractEvent<{
      _src: string;
      _dst: string;
      _sendAmount: BN;
      _recvAmount: BN;
      0: string;
      1: string;
      2: BN;
      3: BN;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
