import BasicAdapter from "@renproject/sol/build/chaosnet/BasicAdapter.json";
import GatewayLogic from "@renproject/sol/build/chaosnet/GatewayLogicV1.json";
import GatewayRegistry from "@renproject/sol/build/chaosnet/GatewayRegistry.json";
import RenERC20 from "@renproject/sol/build/chaosnet/RenERC20LogicV1.json";
import { AbiItem } from "web3-utils";

import { CastNetwork, Contract } from "./network";

const networkID = 1;

// mintAuthority is generated by
// > utils.toChecksumAddress(utils.pubToAddress("... public key ...", true).toString("hex"))

export const renChaosnet = CastNetwork({
    version: "1.0.0",
    name: "chaosnet" as "chaosnet",
    chain: "main",
    isTestnet: false,
    label: "Chaosnet",
    chainLabel: "Mainnet",
    networkID,
    infura: "https://mainnet.infura.io",
    etherscan: "https://etherscan.io",
    addresses: {
        GatewayRegistry: {
            address: GatewayRegistry.networks[networkID].address,
            abi: GatewayRegistry.abi as AbiItem[],
            artifact: GatewayRegistry as Contract,
        },
        RenERC20: {
            abi: RenERC20.abi as AbiItem[],
            artifact: RenERC20 as Contract,
        },
        Gateway: {
            abi: GatewayLogic.abi as AbiItem[],
            artifact: GatewayLogic as Contract,
        },
        BasicAdapter: {
            address: BasicAdapter.networks[networkID].address,
            abi: BasicAdapter.abi as AbiItem[],
            artifact: BasicAdapter as Contract,
        },
    },
});
