import BasicAdapter from "@renproject/sol/build/testnet/BasicAdapter.json";
import GatewayLogic from "@renproject/sol/build/testnet/GatewayLogicV1.json";
import GatewayRegistry from "@renproject/sol/build/testnet/GatewayRegistry.json";
import RenERC20 from "@renproject/sol/build/testnet/RenERC20LogicV1.json";
import { AbiItem } from "web3-utils";

import { CastNetwork, Contract } from "./network";

const networkID = 42;

// mintAuthority is generated by
// > utils.toChecksumAddress(utils.pubToAddress("... public key ...", true).toString("hex"))

export const renTestnet = CastNetwork({
    version: "1.0.0",
    name: "testnet" as "testnet",
    chain: "kovan",
    isTestnet: true,
    label: "Testnet",
    chainLabel: "Kovan",
    networkID,
    infura: "https://kovan.infura.io",
    etherscan: "https://kovan.etherscan.io",
    addresses: {
        GatewayRegistry: {
            address: GatewayRegistry.networks[networkID].address,
            abi: GatewayRegistry.abi as AbiItem[],
            artifact: GatewayRegistry as Contract,
        },
        RenERC20: {
            abi: RenERC20.abi as AbiItem[],
            artifact: RenERC20 as Contract,
        },
        Gateway: {
            abi: GatewayLogic.abi as AbiItem[],
            artifact: GatewayLogic as Contract,
        },
        BasicAdapter: {
            address: BasicAdapter.networks[networkID].address,
            abi: BasicAdapter.abi as AbiItem[],
            artifact: BasicAdapter as Contract,
        },
    },
});
